import { act } from 'react'
import { createRoot, type Root } from 'react-dom/client'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { getConstraintOverlay } from '../game/rules'
import { AcademyScreen } from './AcademyScreen'
import { lessons, teachingScenes, teachingPoses, poseExclusions, quizCell, lessonTierFor, trialFrames, confirmedCells, outsideProof, shapeFrames, type LessonTechnique } from '../data/lessons'

let host: HTMLDivElement, root: Root
const exit = vi.fn(), play = vi.fn()
function displayedCrosses() { return [...host.querySelectorAll('.teaching-cell:has(.teaching-x)')].map((el) => Number(el.getAttribute('data-cell'))).sort((a, b) => a - b) }
const click = (selector: string) => act(() => host.querySelector<HTMLButtonElement>(selector)!.click())
function choose(technique: LessonTechnique) {
  click(`[data-tier="${lessonTierFor(technique).id}"]`)
  click(`[data-technique="${technique}"]`)
}
function finishDemo() {
  let guard = 0
  while (!host.querySelector('.next-step')?.textContent?.match(/判斷一格|換你解殘局|兩種都看了/) && guard++ < 50) click('.next-step')
  expect(guard).toBeLessThan(50)
}
function finishEndgame() {
  let guard = 0
  while (host.querySelector('.trial-next') && guard++ < 20) click('.trial-next')
  expect(guard).toBeLessThan(20)
}
function finishLesson(technique: LessonTechnique) {
  choose(technique); finishDemo(); click('.next-step')
  if (technique === 'combination') finishEndgame(); else click('.answer-yes')
  click('.continue-practice')
  const scene = teachingScenes[technique][1]
  if (technique === 'combination') finishEndgame()
  else click(scene.targets.includes(quizCell(scene, technique, 1)) ? '.answer-yes' : '.answer-no')
}
beforeEach(() => {
  Object.assign(globalThis, { IS_REACT_ACT_ENVIRONMENT: true })
  host = document.createElement('div'); document.body.append(host)
  root = createRoot(host); act(() => root.render(<AcademyScreen onExit={exit} onPlay={play} />))
  exit.mockClear(); play.mockClear()
})
afterEach(() => { act(() => root.unmount()); host.remove(); vi.useRealTimers() })

it.each([
  ['triple', '進階', 'bend'],
  ['reverse', '挑戰', 'hall2'],
] as const)('continues from %s into the next difficulty without leaving the classroom', (technique, nextName, firstTechnique) => {
  finishLesson(technique)
  expect(host.querySelector('.continue-practice')?.textContent).toBe(`繼續學${nextName} →`)
  expect(host.querySelector('.academy-play')?.textContent).toBe('開始遊戲')
  click('.continue-practice')
  expect(host.querySelector(`[data-technique="${firstTechnique}"]`)?.getAttribute('aria-pressed')).toBe('true')
  expect(host.querySelector('.demo-progress small')?.textContent).toContain('第 1')
  expect(host.querySelector('.quiz-feedback')).toBeNull()
  expect(host.querySelector('.course-toggle')?.getAttribute('aria-expanded')).toBe('false')
  expect(JSON.parse(localStorage.getItem('jellySudokuAcademy.v1')!)).toContain(technique)
  expect(exit).not.toHaveBeenCalled()
  expect(play).not.toHaveBeenCalled()
})
it('lets players choose to play after a difficulty or choose another course', () => {
  finishLesson('triple')
  click('.change-learning-level')
  expect(host.querySelector('.course-toggle')?.getAttribute('aria-expanded')).toBe('true')
  click('[aria-label="關閉選課"]')
  click('.academy-play')
  expect(play).toHaveBeenCalledOnce()
  expect(exit).not.toHaveBeenCalled()
})
it('offers play when the final challenge lesson is finished', () => {
  finishLesson('combination')
  expect(host.querySelector('.continue-practice')?.textContent).toBe('開始遊戲')
  expect(host.querySelector('.academy-play')).toBeNull()
  click('.continue-practice')
  expect(play).toHaveBeenCalledOnce()
  expect(exit).not.toHaveBeenCalled()
})

it('starts at basic difficulty and supports full-board autoplay, pause, previous and comparison', () => {
  expect(host.querySelectorAll('.lesson-tiers button')).toHaveLength(3)
  expect(host.querySelector('[data-tier="basic"]')?.getAttribute('aria-pressed')).toBe('true')
  expect(host.querySelectorAll('.tier-lessons button')).toHaveLength(3)
  expect(host.querySelectorAll('.teaching-x')).toHaveLength(0)
  click('.next-step')
  expect(host.querySelectorAll('.teaching-x')).toHaveLength(teachingScenes.line[0].targets.length)
  vi.useFakeTimers()
  choose('pair')
  act(() => vi.advanceTimersByTime(3500))
  expect(host.querySelectorAll('.trial')).toHaveLength(1)
  click('.playback-toggle')
  act(() => vi.advanceTimersByTime(7000))
  expect(host.querySelectorAll('.trial')).toHaveLength(1)
  click('.previous-step')
  expect(host.querySelectorAll('.trial')).toHaveLength(0)
  finishDemo()
  expect(host.querySelectorAll('.teaching-board')).toHaveLength(1)
  expect(host.querySelectorAll('.comparison-switcher button')).toHaveLength(3)
  expect(host.querySelectorAll('.teaching-x')).toHaveLength(4)
  const board = host.querySelector('.teaching-matrix')
  for (let pose = 0; pose < 2; pose++) {
    click(`[data-pose="${pose}"]`)
    expect(host.querySelector('.teaching-matrix')).toBe(board)
    expect(host.querySelectorAll('.trial')).toHaveLength(1)
    expect(host.querySelectorAll('.teaching-x')).toHaveLength(4)
  }
  click('[data-pose="common"]')
  expect(host.querySelectorAll('.trial')).toHaveLength(0)
  for (const board of host.querySelectorAll('.teaching-board')) expect(board.querySelectorAll('.teaching-cell')).toHaveLength(36)
  click('.playback-toggle')
  expect(host.querySelector('.demo-progress small')?.textContent).toContain('第 1')
  choose('line')
  act(() => vi.advanceTimersByTime(3500))
  expect(host.querySelector('.demo-progress small')?.textContent).toContain('第 2')
})
it('requires two one-cell answers for every lesson and saves completion separately from the game', () => {
  for (const lesson of lessons.filter((l) => l.technique !== 'combination')) {
    choose(lesson.technique)
    expect(host.querySelectorAll('.teaching-cell')).toHaveLength(teachingScenes[lesson.technique][0].level.size ** 2)
    expect(host.querySelectorAll('.teaching-x')).toHaveLength(0)
    finishDemo(); click('.next-step')
    expect(host.querySelectorAll('.question-bubble')).toHaveLength(1)
    expect(host.querySelectorAll('.teaching-x')).toHaveLength(0)
    expect(host.querySelectorAll('.candidate-ring')).toHaveLength(teachingScenes[lesson.technique][0].sources.length)
    expect(host.querySelectorAll('.earlier-jelly')).toHaveLength(teachingScenes[lesson.technique][0].board.filter((cell) => cell === 'jelly').length)
    expect(host.querySelectorAll('.teaching-cell')).toHaveLength(teachingScenes[lesson.technique][0].level.size ** 2)
    expect(host.querySelector('.lesson-caution')).toBeNull()
    click('.answer-no')
    expect(host.querySelector('.quiz-feedback')?.textContent).toContain('再看一次')
    expect(JSON.parse(localStorage.getItem('jellySudokuAcademy.v1') ?? '[]')).not.toContain(lesson.technique)
    click('.answer-yes')
    expect(host.querySelector('.quiz-feedback')?.textContent).toContain('判斷正確')
    expect(JSON.parse(localStorage.getItem('jellySudokuAcademy.v1') ?? '[]')).not.toContain(lesson.technique)
    click('.continue-practice')
    const scene = teachingScenes[lesson.technique][1]
    expect(host.querySelectorAll('.teaching-x')).toHaveLength(0)
    expect(host.querySelectorAll('.candidate-ring')).toHaveLength(scene.sources.length)
    const expected = scene.targets.includes(quizCell(scene, lesson.technique, 1))
    click(expected ? '.answer-yes' : '.answer-no')
    expect(host.querySelector('.quiz-feedback')?.textContent).toContain('判斷正確')
    expect(host.querySelector('.lesson-caution')).not.toBeNull()
  }
  finishLesson('combination')
  expect(JSON.parse(localStorage.getItem('jellySudokuAcademy.v1')!)).toHaveLength(9)
  expect(localStorage.getItem('jellySudokuSave.v1')).toBeNull()
  act(() => root.render(<AcademyScreen key="reload" onExit={exit} onPlay={play} />))
  expect(host.querySelector('.subpage-header')?.textContent).toContain('9 / 9')
})
it('replays the current second example and permits a corrected answer', () => {
  choose('pair'); finishDemo(); click('.next-step'); click('.answer-yes'); click('.continue-practice')
  const scene = teachingScenes.pair[1], q = quizCell(scene, 'pair', 1)
  const expected = scene.targets.includes(q)
  expect(host.querySelector(`[data-cell="${q}"]`)?.classList.contains('question')).toBe(true)
  click(expected ? '.answer-no' : '.answer-yes')
  click('.replay-example')
  expect(host.querySelectorAll('.source')).toHaveLength(scene.sources.length)
  finishDemo(); click('.next-step')
  expect(host.querySelector(`[data-cell="${q}"]`)?.classList.contains('question')).toBe(true)
  click(expected ? '.answer-yes' : '.answer-no')
  expect(host.querySelector('.quiz-feedback.correct')).not.toBeNull()
})
it('opens a linked lesson at its difficulty and respects reduced motion', () => {
  vi.stubGlobal('matchMedia', () => ({ matches: true }))
  act(() => root.render(<AcademyScreen key="direct" initialTechnique="hall3" onExit={exit} onPlay={play} />))
  expect(host.querySelector('[data-tier="challenge"]')?.getAttribute('aria-pressed')).toBe('true')
  expect(host.querySelector('[data-technique="hall3"]')?.getAttribute('aria-pressed')).toBe('true')
  expect(host.querySelectorAll('.tier-lessons button')).toHaveLength(3)
  expect(host.querySelector('.playback-toggle')?.textContent).toBe('播放示範')
  click('[aria-label="離開定石教室"]')
  expect(exit).toHaveBeenCalledOnce()
  vi.unstubAllGlobals()
})
it('allows any difficulty without unlocking and clears an unfinished exercise when switching', () => {
  choose('pair'); finishDemo(); click('.next-step'); click('.answer-no')
  click('[data-tier="challenge"]')
  expect(host.querySelector('.quiz-feedback')).toBeNull()
  expect(host.querySelector('.demo-progress small')?.textContent).toContain('第 1')
  expect(host.querySelector('[data-technique="hall2"]')?.getAttribute('aria-pressed')).toBe('true')
  expect(host.querySelectorAll('.question-bubble')).toHaveLength(0)
  expect(host.querySelectorAll('.lesson-tiers button:disabled')).toHaveLength(0)
  click('[data-tier="basic"]')
  expect(host.querySelector('[data-technique="line"]')?.getAttribute('aria-pressed')).toBe('true')
  click('[data-technique="pair"]')
  expect(host.querySelector('[data-technique="pair"]')?.getAttribute('aria-pressed')).toBe('true')
  finishDemo(); click('.next-step'); click('.answer-yes'); click('.continue-practice')
  const scene = teachingScenes.pair[1]
  click(scene.targets.includes(quizCell(scene, 'pair', 1)) ? '.answer-yes' : '.answer-no')
  expect(host.querySelector('[data-tier="basic"]')?.textContent).toContain('1 / 3 已學會')
  expect(host.querySelector('.continue-practice')?.textContent).toContain('下一個基礎技巧')
  click('.continue-practice')
  expect(host.querySelector('[data-technique="triple"]')?.getAttribute('aria-pressed')).toBe('true')
})
it('explains all three L exclusions and labels the applicable rule for each possibility', () => {
  choose('bend'); finishDemo()
  expect(host.querySelectorAll('.teaching-board')).toHaveLength(1)
  expect(host.querySelectorAll('.comparison-switcher [data-pose]')).toHaveLength(4)
  click('.view-colour')
  expect(host.querySelector('.view-outside')?.textContent).toBe('從旁邊看')
  const labels: (string | null)[] = []
  for (let pose = 0; pose < 3; pose++) {
    click(`[data-pose="${pose}"]`)
    expect(host.querySelectorAll('.teaching-x')).toHaveLength(3)
    expect(host.querySelectorAll('.teaching-rule')).toHaveLength(3)
    labels.push(...[...host.querySelectorAll('.teaching-rule')].map((el) => el.textContent))
  }
  expect(labels).toEqual(expect.arrayContaining(['同排', '同列', '相鄰']))
})

it('pauses playback while choosing a course and closes the picker on selection or Escape', () => {
  vi.useFakeTimers()
  click('.course-toggle')
  expect(host.querySelector('.course-toggle')?.getAttribute('aria-expanded')).toBe('true')
  act(() => vi.advanceTimersByTime(7000))
  expect(host.querySelector('.demo-progress small')?.textContent).toContain('第 1')
  act(() => document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true })))
  expect(host.querySelector('.course-toggle')?.getAttribute('aria-expanded')).toBe('false')
  click('.course-toggle')
  click('[data-tier="advanced"]')
  expect(host.querySelector('.course-toggle')?.getAttribute('aria-expanded')).toBe('true')
  expect(host.querySelector('.playback-toggle')?.textContent).toBe('播放示範')
  choose('pair')
  expect(host.querySelector('.course-toggle')?.getAttribute('aria-expanded')).toBe('false')
  act(() => vi.advanceTimersByTime(3500))
  expect(host.querySelector('.demo-progress small')?.textContent).toContain('第 2')
})
it('shows the A branch, restores every temporary placement, then confirms B and completes the endgame', () => {
  choose('combination')
  const scene = teachingScenes.combination[0], frames = trialFrames(scene), confirmed = confirmedCells(scene)
  expect(host.querySelectorAll('.known-jelly')).toHaveLength(confirmed.length)
  expect(host.querySelectorAll('.candidate-letter')).toHaveLength(2)
  expect(displayedCrosses()).toEqual([...getConstraintOverlay(scene.board, scene.level)].sort((a, b) => a - b))
  expect(host.querySelector('.board-context')?.textContent).toContain('輔助開')
  for (const frame of frames.slice(1)) {
    click('.next-step')
    expect(host.querySelector('.demo-progress small')?.textContent).toContain(frame.name)
    expect(host.querySelector('.teaching-caption')?.textContent).toContain(frame.caption)
    expect(host.querySelectorAll('.known-jelly')).toHaveLength(confirmed.length)
    const visible = scene.board.map((cell, i) => frame.pose.includes(i) ? 'jelly' as const : cell)
    const excluded = new Set([...getConstraintOverlay(visible, scene.level), ...frame.blocked])
    expect(displayedCrosses()).toEqual([...excluded].filter((i) => visible[i] !== 'jelly').sort((a, b) => a - b))
    expect(host.querySelector('.teaching-cell:has(img):has(.teaching-x)')).toBeNull()
    if (frame.kind === 'restore') {
      expect(host.querySelector('.hypothesis, .trial')).toBeNull()
      expect(displayedCrosses()).toEqual([...getConstraintOverlay(scene.board, scene.level)].sort((a, b) => a - b))
      expect(host.querySelectorAll('.candidate-ring')).toHaveLength(2)
      expect(host.querySelectorAll('.teaching-cell img')).toHaveLength(confirmed.length)
    }
    if (frame.confirmed) expect(host.querySelector('.hypothesis, .trial')).toBeNull()
  }
  expect(host.querySelectorAll('.teaching-cell img')).toHaveLength(scene.level.size)
  click('.playback-toggle')
  expect(host.querySelectorAll('.teaching-cell img')).toHaveLength(confirmed.length)
  expect(host.querySelector('.hypothesis, .trial')).toBeNull()
})
it('guides both endgames with one action, allowing board choices only after the correct rollback stage', () => {
  choose('combination'); finishDemo(); click('.next-step')
  for (let exercise = 0; exercise < 2; exercise++) {
    const scene = teachingScenes.combination[exercise], confirmed = confirmedCells(scene), frames = trialFrames(scene)
    const failure = frames.findIndex((frame) => frame.kind === 'failure')
    expect(host.querySelector('.answer-yes, .answer-no, .trial-place')).toBeNull()
    expect(host.querySelectorAll('.trial-progress li')).toHaveLength(4)
    expect(host.querySelector('.trial-progress button')).toBeNull()
    expect(host.querySelector('.trial-progress [aria-current=step]')?.textContent).toContain('試放')
    expect(host.querySelector('.trial-next')?.textContent).toBe('試放 A 這格')
    expect(host.querySelectorAll('button.teaching-cell')).toHaveLength(1)
    expect(host.querySelector(`button[data-cell="${scene.sources[1]}"]`)).toBeNull()
    expect(host.querySelector('.teaching-board')?.getAttribute('role')).toBe('group')
    click(exercise === 0 ? `button[data-cell="${scene.sources[0]}"]` : '.trial-next')
    if (exercise === 0) expect(document.activeElement).toBe(host.querySelector('.trial-next'))
    expect(host.querySelectorAll('.trial')).toHaveLength(1)
    expect(host.querySelector('.trial-next')?.textContent).toBe('繼續推導')
    expect(host.querySelector('.trial-progress [aria-current=step]')?.textContent).toContain('找矛盾')
    for (const frame of frames.slice(frames.findIndex((f) => f.kind === 'trial') + 1, failure + 1)) {
      click('.trial-next')
      expect(host.querySelector('.teaching-caption')?.textContent).toContain(frame.caption)
      expect(host.querySelectorAll('.trial')).toHaveLength(frame.pose.length)
      expect(host.querySelector('button.teaching-cell')).toBeNull()
    }
    expect(host.querySelector('.trial-next')?.textContent).toBe('撤回這次試放')
    expect(host.querySelector('.trial-progress [aria-current=step]')?.textContent).toContain('撤回')
    click('.trial-next')
    expect(host.querySelector('.hypothesis, .trial')).toBeNull()
    expect(host.querySelectorAll('.teaching-cell img')).toHaveLength(confirmed.length)
    expect(displayedCrosses()).toEqual([...getConstraintOverlay(scene.board, scene.level)].sort((a, b) => a - b))
    expect(host.querySelector('.trial-next')?.textContent).toBe('改選 B 這格')
    expect(host.querySelector('.trial-progress [aria-current=step]')?.textContent).toContain('改選')
    expect(host.querySelector(`button[data-cell="${scene.sources[0]}"]`)).toBeNull()
    click(exercise === 0 ? `button[data-cell="${scene.sources[1]}"]` : '.trial-next')
    expect(host.querySelectorAll('.confirmed-placement')).toHaveLength(1)
    expect(host.querySelector('.trial-next')?.textContent).toBe('接著完成盤面')
    expect(JSON.parse(localStorage.getItem('jellySudokuAcademy.v1') ?? '[]')).not.toContain('combination')
    finishEndgame()
    expect(host.querySelectorAll('.teaching-cell img')).toHaveLength(scene.level.size)
    expect(host.querySelector('.trial-complete')?.textContent).toContain('殘局完成')
    if (!exercise) {
      expect(host.querySelectorAll('.trial-progress .is-done')).toHaveLength(4)
      click('.continue-practice')
    }
  }
  expect(JSON.parse(localStorage.getItem('jellySudokuAcademy.v1') ?? '[]')).toContain('combination')
  click('.replay-example')
  expect(host.querySelector('.hypothesis, .trial')).toBeNull()
  expect(host.querySelectorAll('.known-jelly')).toHaveLength(confirmedCells(teachingScenes.combination[1]).length)
  finishDemo(); click('.next-step')
  expect(host.querySelector('.trial-next')?.textContent).toBe('試放 A 這格')
})
it('clears the entire unfinished trial on replay or course selection', () => {
  choose('combination'); finishDemo(); click('.next-step'); click('.trial-next'); click('.trial-next')
  expect(host.querySelectorAll('.trial').length).toBeGreaterThan(1)
  click('.replay-example'); finishDemo(); click('.next-step')
  expect(host.querySelector('.trial-next')?.textContent).toBe('試放 A 這格')
  expect(host.querySelector('.hypothesis, .trial')).toBeNull()
  click('.trial-next'); choose('pair')
  expect(host.querySelector('.trial-progress, .guided-choice, .hypothesis, .trial-next')).toBeNull()
  expect(displayedCrosses()).toEqual([])
  expect(localStorage.getItem('jellySudokuAcademy.v1')).toBeNull()
})
it('starts with the entire Z colour and preserves demonstration crosses, clues and practice answers', () => {
  choose('zigzag')
  const scene = teachingScenes.zigzag[0]
  const originalBoard = [...scene.board]
  const displayed = () => [...host.querySelectorAll('.teaching-cell:has(.teaching-x)')].map((el) => Number(el.getAttribute('data-cell'))).sort((a, b) => a - b)
  expect(scene.sources).toEqual(scene.level.regions.flatMap((region, i) => region === scene.level.regions[scene.sources[0]] ? [i] : []))
  expect(displayed()).toEqual([])
  expect(host.querySelector('.teaching-board')?.getAttribute('aria-label')).not.toContain('格畫叉')
  expect(host.querySelectorAll('.candidate-ring')).toHaveLength(scene.sources.length)
  expect(host.querySelector('.prior-x, .prior-mark')).toBeNull()
  expect(host.querySelector('.board-context')?.textContent).not.toContain('淡叉')
  expect(host.querySelector('.board-context')?.textContent).toContain('圈圈＝該顏色所有格子')
  expect(host.querySelector('.board-context')?.textContent).toContain('×＝本次排除的位置')
  click('.next-step')
  const excluded = poseExclusions(scene, 'zigzag', teachingPoses(scene, 'zigzag')[0])
  expect(displayed()).toEqual([...excluded].sort((a, b) => a - b))
  expect(host.querySelector('.teaching-board')?.getAttribute('aria-label')).toContain(`本次排除 ${excluded.length} 格畫叉`)
  click('.previous-step')
  expect(displayed()).toEqual([])
  finishDemo()
  expect(displayed()).toEqual([...scene.targets].sort((a, b) => a - b))
  click('.next-step')
  expect(displayed()).toEqual([])
  expect(host.querySelector('.question .teaching-x')).toBeNull()
  expect(host.querySelectorAll('.question-bubble')).toHaveLength(1)
  expect(host.querySelectorAll('.candidate-ring')).toHaveLength(scene.sources.length)
  expect(host.querySelector('.board-context')?.textContent).not.toContain('×')
  click('.answer-no')
  expect(host.querySelector('.quiz-feedback')?.textContent).toContain('再看一次')
  click('.answer-yes')
  expect(host.querySelector('.quiz-feedback.correct')).not.toBeNull()
  click('.replay-example')
  expect(displayed()).toEqual([])
  expect(scene.board).toEqual(originalBoard)
})
it('ignores removed lessons in the displayed total but retains their saved records', () => {
  localStorage.setItem('jellySudokuAcademy.v1', JSON.stringify(['placed', 'single', 'common', 'line']))
  act(() => root.render(<AcademyScreen key="legacy" initialTechnique="common" onExit={exit} onPlay={play} />))
  expect(host.querySelector('.subpage-header')?.textContent).toContain('1 / 9')
  expect(host.querySelector('[data-technique="line"]')?.getAttribute('aria-pressed')).toBe('true')
  choose('pair'); finishDemo(); click('.next-step'); click('.answer-yes'); click('.continue-practice')
  const scene = teachingScenes.pair[1]
  click(scene.targets.includes(quizCell(scene, 'pair', 1)) ? '.answer-yes' : '.answer-no')
  expect(JSON.parse(localStorage.getItem('jellySudokuAcademy.v1')!)).toEqual(expect.arrayContaining(['placed', 'single', 'common', 'line', 'pair']))
})

it.each(['bend', 'zigzag'] as const)('guides %s through both views before practice, with full assistance for outside trials', (technique) => {
  choose(technique)
  const scene = teachingScenes[technique][0], snapshot = JSON.stringify(scene), frames = shapeFrames(scene, technique)
  expect(host.querySelector('.view-outside')).toBeNull()
  expect(host.querySelector('.proof-directions [aria-current=step]')?.textContent).toContain('從顏色看')
  expect(displayedCrosses()).toEqual([])
  for (const [index, frame] of frames.entries()) {
    if (index) click('.next-step')
    expect(host.querySelector('.phase-practice')).toBeNull()
    expect(host.querySelector('.teaching-caption')?.textContent).toContain(frame.caption)
    if (frame.view === 'outside' && frame.hypothesis !== undefined) {
      const visible = scene.board.map((cell, i) => frame.pose.includes(i) ? 'jelly' as const : cell)
      expect(displayedCrosses()).toEqual([...getConstraintOverlay(visible, scene.level)].sort((a, b) => a - b))
      expect(scene.sources.every((i) => displayedCrosses().includes(i))).toBe(true)
      expect(host.querySelector('.board-context')?.textContent).toContain('輔助開')
      expect(host.querySelectorAll('.teaching-cell img')).toHaveLength(1)
      expect(host.querySelectorAll('.teaching-rule')).toHaveLength(scene.sources.length)
      expect(host.querySelector('.teaching-cell:has(img):has(.teaching-x)')).toBeNull()
    }
    if (frame.view === 'colour' && frame.kind === 'conclusion') {
      expect(host.querySelector('.next-step')?.textContent).toBe('接著看另一種方法 →')
      expect(host.querySelector('.view-outside')).toBeNull()
    }
    if (frame.view === 'outside' && frame.kind === 'intro') {
      expect(displayedCrosses()).toEqual([])
      expect(host.querySelector('.hypothesis, .trial')).toBeNull()
      expect(host.querySelector('.proof-directions')?.textContent).toContain('✓')
    }
  }
  expect(host.querySelector('.next-step')?.textContent).toBe('兩種都看了，試試看')
  expect(displayedCrosses()).toEqual([...scene.targets].sort((a, b) => a - b))
  expect(host.querySelectorAll('.candidate-ring')).toHaveLength(scene.sources.length)
  click('[data-pose="0"]')
  expect(host.querySelector(`[data-cell="${scene.targets[0]}"] img`)).not.toBeNull()
  click('[data-pose="common"]')
  expect(host.querySelector('.hypothesis')).toBeNull()
  click('.view-colour')
  expect(host.querySelector('.demo-progress small')?.textContent).toContain('兩種都看了')
  expect(host.querySelector('.assist-cell')).toBeNull()
  click('.view-outside')
  click('.next-step')
  expect(host.querySelector('.phase-practice')).not.toBeNull()
  expect(JSON.stringify(scene)).toBe(snapshot)
})
it.each(['bend', 'zigzag'] as const)('autoplays both %s views and restores the first direction on replay', (technique) => {
  vi.useFakeTimers(); choose(technique)
  const frames = shapeFrames(teachingScenes[technique][0], technique)
  for (let i = 1; i < frames.length; i++) act(() => vi.advanceTimersByTime(3500))
  expect(host.querySelector('.next-step')?.textContent).toBe('兩種都看了，試試看')
  expect(host.querySelector('.hypothesis')).toBeNull()
  click('.playback-toggle')
  expect(host.querySelector('.demo-progress small')?.textContent).toContain('① 從顏色看')
  expect(displayedCrosses()).toEqual([])
  expect(host.querySelector('.proof-directions [aria-current=step]')?.textContent).toContain('從顏色看')
})
it.each(['bend', 'zigzag'] as const)('uses the opposite view for %s practice without rejecting surviving colour positions', (technique) => {
  choose(technique); finishDemo(); click('.next-step')
  const first = teachingScenes[technique][0]
  click('.view-outside')
  const assumed = quizCell(first, technique, 0)
  expect(displayedCrosses()).toEqual([...getConstraintOverlay(first.board.map((cell, i) => i === assumed ? 'jelly' as const : cell), first.level)].sort((a, b) => a - b))
  expect(host.querySelector('.board-context')?.textContent).toContain('輔助開')
  click('.view-colour')
  expect(displayedCrosses()).toEqual([])
  expect(host.querySelectorAll('.question-bubble')).toHaveLength(1)
  click('.view-outside'); click('.answer-yes')
  expect(host.querySelector('.hypothesis')).toBeNull()
  click('.continue-practice')
  const second = teachingScenes[technique][1], q = quizCell(second, technique, 1)
  expect(second.targets).not.toContain(q)
  click('.view-outside')
  expect(displayedCrosses()).toEqual([...getConstraintOverlay(second.board.map((cell, i) => i === q ? 'jelly' as const : cell), second.level)].sort((a, b) => a - b))
  expect(host.querySelectorAll('.source.blocked')).toHaveLength(outsideProof(second, q).blocked.length)
  expect(host.querySelectorAll('.candidate-ring').length).toBeGreaterThan(0)
  expect(host.querySelector('.teaching-caption')?.textContent).toContain('還不能排除')
  click('.answer-no')
  expect(host.querySelector('.quiz-feedback.correct')).not.toBeNull()
  expect(host.querySelector('.hypothesis')).toBeNull()
  click('.replay-example')
  expect(displayedCrosses()).toEqual([])
  expect(host.querySelector('.proof-directions [aria-current=step]')?.textContent).toContain('從顏色看')
})
