import { act } from 'react'
import { createRoot, type Root } from 'react-dom/client'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { AcademyScreen } from './AcademyScreen'
import { lessons, teachingScenes, teachingPoses, poseExclusions, quizCell, lessonTierFor, type LessonTechnique } from '../data/lessons'

let host: HTMLDivElement, root: Root
const exit = vi.fn()
const click = (selector: string) => act(() => host.querySelector<HTMLButtonElement>(selector)!.click())
function choose(technique: LessonTechnique) {
  click(`[data-tier="${lessonTierFor(technique).id}"]`)
  click(`[data-technique="${technique}"]`)
}
function finishDemo() {
  let guard = 0
  while (!host.querySelector('.next-step')?.textContent?.includes('判斷一格') && guard++ < 50) click('.next-step')
  expect(guard).toBeLessThan(50)
}
beforeEach(() => {
  Object.assign(globalThis, { IS_REACT_ACT_ENVIRONMENT: true })
  host = document.createElement('div'); document.body.append(host)
  root = createRoot(host); act(() => root.render(<AcademyScreen onExit={exit} />))
  exit.mockClear()
})
afterEach(() => { act(() => root.unmount()); host.remove(); vi.useRealTimers() })

it('starts at basic difficulty and supports full-board autoplay, pause, previous and comparison', () => {
  expect(host.querySelectorAll('.lesson-tiers button')).toHaveLength(3)
  expect(host.querySelector('[data-tier="basic"]')?.getAttribute('aria-pressed')).toBe('true')
  expect(host.querySelectorAll('.tier-lessons button')).toHaveLength(3)
  expect(host.querySelectorAll('.teaching-x')).toHaveLength(0)
  click('.next-step')
  expect(host.querySelectorAll('.teaching-x')).toHaveLength(teachingScenes.line[0].targets.length)
  vi.useFakeTimers()
  choose('pair')
  act(() => vi.advanceTimersByTime(3500))
  expect(host.querySelectorAll('.trial')).toHaveLength(1)
  click('.playback-toggle')
  act(() => vi.advanceTimersByTime(7000))
  expect(host.querySelectorAll('.trial')).toHaveLength(1)
  click('.previous-step')
  expect(host.querySelectorAll('.trial')).toHaveLength(0)
  finishDemo()
  expect(host.querySelectorAll('.teaching-board')).toHaveLength(1)
  expect(host.querySelectorAll('.comparison-switcher button')).toHaveLength(3)
  expect(host.querySelectorAll('.teaching-x')).toHaveLength(4)
  const board = host.querySelector('.teaching-matrix')
  for (let pose = 0; pose < 2; pose++) {
    click(`[data-pose="${pose}"]`)
    expect(host.querySelector('.teaching-matrix')).toBe(board)
    expect(host.querySelectorAll('.trial')).toHaveLength(1)
    expect(host.querySelectorAll('.teaching-x')).toHaveLength(4)
  }
  click('[data-pose="common"]')
  expect(host.querySelectorAll('.trial')).toHaveLength(0)
  for (const board of host.querySelectorAll('.teaching-board')) expect(board.querySelectorAll('.teaching-cell')).toHaveLength(36)
  click('.playback-toggle')
  expect(host.querySelector('.demo-progress small')?.textContent).toContain('第 1')
  choose('line')
  act(() => vi.advanceTimersByTime(3500))
  expect(host.querySelector('.demo-progress small')?.textContent).toContain('第 2')
})
it('requires two one-cell answers for every lesson and saves completion separately from the game', () => {
  for (const lesson of lessons) {
    choose(lesson.technique)
    expect(host.querySelectorAll('.teaching-cell')).toHaveLength(teachingScenes[lesson.technique][0].level.size ** 2)
    finishDemo(); click('.next-step')
    expect(host.querySelectorAll('.question-bubble')).toHaveLength(1)
    expect(host.querySelectorAll('.teaching-cell')).toHaveLength(teachingScenes[lesson.technique][0].level.size ** 2)
    expect(host.querySelector('.lesson-caution')).toBeNull()
    click('.answer-no')
    expect(host.querySelector('.quiz-feedback')?.textContent).toContain('再看一次')
    expect(JSON.parse(localStorage.getItem('jellySudokuAcademy.v1') ?? '[]')).not.toContain(lesson.technique)
    click('.answer-yes')
    expect(host.querySelector('.quiz-feedback')?.textContent).toContain('判斷正確')
    expect(JSON.parse(localStorage.getItem('jellySudokuAcademy.v1') ?? '[]')).not.toContain(lesson.technique)
    click('.continue-practice')
    const scene = teachingScenes[lesson.technique][1]
    const expected = scene.targets.includes(quizCell(scene, lesson.technique, 1))
    click(expected ? '.answer-yes' : '.answer-no')
    expect(host.querySelector('.quiz-feedback')?.textContent).toContain('判斷正確')
    expect(host.querySelector('.lesson-caution')).not.toBeNull()
  }
  expect(JSON.parse(localStorage.getItem('jellySudokuAcademy.v1')!)).toHaveLength(9)
  expect(localStorage.getItem('jellySudokuSave.v1')).toBeNull()
  act(() => root.render(<AcademyScreen key="reload" onExit={exit} />))
  expect(host.querySelector('.subpage-header')?.textContent).toContain('9 / 9')
})
it('replays the current second example and permits a corrected answer', () => {
  choose('pair'); finishDemo(); click('.next-step'); click('.answer-yes'); click('.continue-practice')
  const scene = teachingScenes.pair[1], q = quizCell(scene, 'pair', 1)
  const expected = scene.targets.includes(q)
  expect(host.querySelector(`[data-cell="${q}"]`)?.classList.contains('question')).toBe(true)
  click(expected ? '.answer-no' : '.answer-yes')
  click('.replay-example')
  expect(host.querySelectorAll('.source')).toHaveLength(scene.sources.length)
  finishDemo(); click('.next-step')
  expect(host.querySelector(`[data-cell="${q}"]`)?.classList.contains('question')).toBe(true)
  click(expected ? '.answer-yes' : '.answer-no')
  expect(host.querySelector('.quiz-feedback.correct')).not.toBeNull()
})
it('opens a linked lesson at its difficulty and respects reduced motion', () => {
  vi.stubGlobal('matchMedia', () => ({ matches: true }))
  act(() => root.render(<AcademyScreen key="direct" initialTechnique="hall3" onExit={exit} />))
  expect(host.querySelector('[data-tier="challenge"]')?.getAttribute('aria-pressed')).toBe('true')
  expect(host.querySelector('[data-technique="hall3"]')?.getAttribute('aria-pressed')).toBe('true')
  expect(host.querySelectorAll('.tier-lessons button')).toHaveLength(3)
  expect(host.querySelector('.playback-toggle')?.textContent).toBe('播放示範')
  click('[aria-label="離開定石教室"]')
  expect(exit).toHaveBeenCalledOnce()
  vi.unstubAllGlobals()
})
it('allows any difficulty without unlocking and clears an unfinished exercise when switching', () => {
  choose('pair'); finishDemo(); click('.next-step'); click('.answer-no')
  click('[data-tier="challenge"]')
  expect(host.querySelector('.quiz-feedback')).toBeNull()
  expect(host.querySelector('.demo-progress small')?.textContent).toContain('第 1')
  expect(host.querySelector('[data-technique="hall2"]')?.getAttribute('aria-pressed')).toBe('true')
  expect(host.querySelectorAll('.question-bubble')).toHaveLength(0)
  expect(host.querySelectorAll('.lesson-tiers button:disabled')).toHaveLength(0)
  click('[data-tier="basic"]')
  expect(host.querySelector('[data-technique="line"]')?.getAttribute('aria-pressed')).toBe('true')
  click('[data-technique="pair"]')
  expect(host.querySelector('[data-technique="pair"]')?.getAttribute('aria-pressed')).toBe('true')
  finishDemo(); click('.next-step'); click('.answer-yes'); click('.continue-practice')
  const scene = teachingScenes.pair[1]
  click(scene.targets.includes(quizCell(scene, 'pair', 1)) ? '.answer-yes' : '.answer-no')
  expect(host.querySelector('[data-tier="basic"]')?.textContent).toContain('1 / 3 已學會')
  expect(host.querySelector('.continue-practice')?.textContent).toContain('下一個基礎技巧')
  click('.continue-practice')
  expect(host.querySelector('[data-technique="triple"]')?.getAttribute('aria-pressed')).toBe('true')
})
it('explains all three L exclusions and labels the applicable rule for each possibility', () => {
  choose('bend'); finishDemo()
  expect(host.querySelectorAll('.teaching-board')).toHaveLength(1)
  expect(host.querySelectorAll('.comparison-switcher button')).toHaveLength(4)
  const labels: (string | null)[] = []
  for (let pose = 0; pose < 3; pose++) {
    click(`[data-pose="${pose}"]`)
    expect(host.querySelectorAll('.teaching-x')).toHaveLength(3)
    expect(host.querySelectorAll('.teaching-rule')).toHaveLength(3)
    labels.push(...[...host.querySelectorAll('.teaching-rule')].map((el) => el.textContent))
  }
  expect(labels).toEqual(expect.arrayContaining(['同排', '同列', '相鄰']))
})

it('pauses playback while choosing a course and closes the picker on selection or Escape', () => {
  vi.useFakeTimers()
  click('.course-toggle')
  expect(host.querySelector('.course-toggle')?.getAttribute('aria-expanded')).toBe('true')
  act(() => vi.advanceTimersByTime(7000))
  expect(host.querySelector('.demo-progress small')?.textContent).toContain('第 1')
  act(() => document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true })))
  expect(host.querySelector('.course-toggle')?.getAttribute('aria-expanded')).toBe('false')
  click('.course-toggle')
  click('[data-tier="advanced"]')
  expect(host.querySelector('.course-toggle')?.getAttribute('aria-expanded')).toBe('true')
  expect(host.querySelector('.playback-toggle')?.textContent).toBe('播放示範')
  choose('pair')
  expect(host.querySelector('.course-toggle')?.getAttribute('aria-expanded')).toBe('false')
  act(() => vi.advanceTimersByTime(3500))
  expect(host.querySelector('.demo-progress small')?.textContent).toContain('第 2')
})
it('teaches the extra value of combining colours by showing a failed assumption', () => {
  choose('combination')
  expect(host.querySelector('.teaching-caption')?.textContent).toContain('還不能確定畫叉')
  click('.next-step')
  expect(host.querySelectorAll('.hypothesis')).toHaveLength(1)
  expect(host.querySelectorAll('.source.blocked').length).toBeGreaterThan(0)
  click('.next-step')
  expect(host.querySelector('.teaching-caption')?.textContent).toMatch(/同一(橫排|直列)/)
  expect(host.querySelectorAll('.contradiction-unit')).toHaveLength(teachingScenes.combination[0].level.size)
  finishDemo()
  expect(host.querySelector('.teaching-caption')?.textContent).toContain('一起看兩色就能確定畫叉')
  const scene = teachingScenes.combination[0]
  expect(host.querySelectorAll('.teaching-x')).toHaveLength(new Set([...scene.targets, ...scene.board.flatMap((cell, i) => cell === 'marked' ? [i] : [])]).size)
})
it('keeps existing crosses through demonstration, previous step and practice using the same mark', () => {
  choose('zigzag')
  const scene = teachingScenes.zigzag[0]
  const prior = scene.board.flatMap((cell, i) => cell === 'marked' ? [i] : [])
  const displayed = () => [...host.querySelectorAll('.teaching-cell:has(.teaching-x)')].map((el) => Number(el.getAttribute('data-cell'))).sort((a, b) => a - b)
  expect(prior.length).toBeGreaterThan(0)
  expect(displayed()).toEqual(prior)
  expect(host.querySelector('.prior-x, .prior-mark')).toBeNull()
  expect(host.querySelector('.board-context')?.textContent).not.toContain('淡叉')
  expect(host.querySelector('.board-context')?.textContent).toContain('×＝不能放水母')
  const existingCross = host.querySelector(`[data-cell="${prior[0]}"] .teaching-x`)
  click('.next-step')
  const excluded = poseExclusions(scene, 'zigzag', teachingPoses(scene, 'zigzag')[0])
  expect(displayed()).toEqual([...new Set([...prior, ...excluded])].sort((a, b) => a - b))
  expect(host.querySelector(`[data-cell="${prior[0]}"] .teaching-x`)).toBe(existingCross)
  click('.previous-step')
  expect(displayed()).toEqual(prior)
  finishDemo(); click('.next-step')
  expect(displayed()).toEqual(prior)
  expect(host.querySelector('.question .teaching-x')).toBeNull()
  expect(host.querySelectorAll('.question-bubble')).toHaveLength(1)
})
it('ignores removed lessons in the displayed total but retains their saved records', () => {
  localStorage.setItem('jellySudokuAcademy.v1', JSON.stringify(['placed', 'single', 'common', 'line']))
  act(() => root.render(<AcademyScreen key="legacy" initialTechnique="common" onExit={exit} />))
  expect(host.querySelector('.subpage-header')?.textContent).toContain('1 / 9')
  expect(host.querySelector('[data-technique="line"]')?.getAttribute('aria-pressed')).toBe('true')
  choose('pair'); finishDemo(); click('.next-step'); click('.answer-yes'); click('.continue-practice')
  const scene = teachingScenes.pair[1]
  click(scene.targets.includes(quizCell(scene, 'pair', 1)) ? '.answer-yes' : '.answer-no')
  expect(JSON.parse(localStorage.getItem('jellySudokuAcademy.v1')!)).toEqual(expect.arrayContaining(['placed', 'single', 'common', 'line', 'pair']))
})
